### ISSUE TITLE
psutil does not compile with go1.6

### ISSUE THREAD

**Issue by mjbrender** [intelsdi-x/snap-plugin-collector-psutil#13] opened 2016-04-07 22:57 UTC
While running the influxdb-grafana example in the framework repo ([here](https://github.com/intelsdi-x/snap/tree/master/examples/influxdb-grafana)) I found psutil does not compile. The error is centered around `psutil/mem.go:88: mem.Shared undefined (type *mem.VirtualMemoryStat has no field or method Shared)`. More complete output is below. 

May relate to #12 given the updates. FYI @intelsdi-x/plugin-maintainers 

```
**** snap plugin build  ****

Source Dir = /Users/mjbrende/.gvm/pkgsets/go1.6/global/src/github.com/intelsdi-x/snap-plugin-publisher-influxdb
Building snap plugin: snap-plugin-publisher-influxdb
getting and building snap-plugin-collector-psutil
# github.com/intelsdi-x/snap-plugin-collector-psutil/psutil
../../../snap-plugin-collector-psutil/psutil/mem.go:88: mem.Shared undefined (type *mem.VirtualMemoryStat has no field or method Shared)
bash -c "./scripts/build.sh /Users/mjbrende/.gvm/pkgsets/go1.6/global/src/github.com/intelsdi-x/snap-plugin-collector-psutil"

****  Snap Plugin Build  ****

Source Dir = /Users/mjbrende/.gvm/pkgsets/go1.6/global/src/github.com/intelsdi-x/snap-plugin-collector-psutil
Building Snap Plugin: snap-plugin-collector-psutil
# github.com/intelsdi-x/snap-plugin-collector-psutil/psutil
psutil/mem.go:88: mem.Shared undefined (type *mem.VirtualMemoryStat has no field or method Shared)
make: *** [all] Error 2
/Library/Developer/CommandLineTools/usr/bin/make dips
bash -c "godep restore"
godep: error restoring dep (github.com/shirou/gopsutil/common): cannot find package "github.com/shirou/gopsutil/common" in any of:
	/Users/mjbrende/.gvm/gos/go1.6/src/github.com/shirou/gopsutil/common (from $GOROOT)
	/Users/mjbrende/.gvm/pkgsets/go1.6/global/src/github.com/shirou/gopsutil/common (from $GOPATH)
godep: Error restoring some deps. Aborting check.
make[1]: *** [deps] Error 1
make: *** [default] Error 2
 Error: failed to get and compile psutil plugin
```

**Comment by mjbrender** [comment] 2016-04-07 22:58
I should mention a `gvm use go1.5.3` and re-running the script works.

**Comment by marcintao** [comment] 2016-07-21 10:15
I have failed to reproduce this issue. For a test I have successfully built  psutil collector using go1.5.3, go1.6.0 and 1.6.2 plain environment (ie: started in a container).

Does this issue still affect you?

**Comment by IRCody** [comment] 2016-08-19 18:22
Closing because it appears to be working (by marcintao's report and is building in travis on 1.6.2).

**Closed by IRCody** 2016-08-19 18:22 UTC
Labels: tracked
